spring:
    application:
        name: spring-boot-server
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=myschema
        username: postgres
        password: 1234
    jpa:
        properties:
            hibernate:
                format-sql: true
        show-sql: true
        hibernate:
            ddl-auto: none
    data:
        redis:
            host: localhost
            port: 6379
    session:
        redis:
            flush-mode: on-save
            namespace: spring:session
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_SECRET}
                        scope:
                            - profile
                            - email
                        redirect-uri: "{baseUrl}/springbootserver/login/oauth2/code/google"

server:
    port: 8080
    forward-headers-strategy: native
    servlet:
        session:
            timeout: 1d
            cookie:
                max-age: 1d

logging:
    level:
        root: warn
# springdoc:
#     api-docs:
#         version: openapi-3-1
#     swagger-ui:
#         display-request-duration: true
#         groups-order: DESC
#         operationsSorter: method
#         disable-swagger-default-url: true
#         use-root-path: true
#         enabled: true
#     show-actuator: true
#     cache:
#         disabled: true
