spring:
    application:
        name: spring-boot-server
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
    jpa:
        properties:
            hibernate:
                format-sql: true
        show-sql: true
        hibernate:
            ddl-auto: create
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_SECRET}
                        scope:
                            - profile
                            - email
server:
    port: 8080

logging:
    level:
        root: warn

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

jwt:
    secret: 8eaff7b2a4eb83db0df94b7bc89bf568119277ded1474f5a378c93cc25b0ad59
    expiration: 5000
    refresh-token:
        expiration: 86400000
